### ISSUE TITLE
better query formatting

### ISSUE THREAD

**Issue by vitaly-t** [BryceKrah/Driver-Babylon.js#11]
this code:

``` js
db.any('INSERT INTO scores (name, score) VALUES (${name}, ${score})',
  {
    name: req.body.name,
    score: req.body.score
 })
```

is the same as this one:

``` js
db.any('INSERT INTO scores (name, score) VALUES (${name}, ${score})', req.body)
```

see [Redundant Named Parameter re-referencing](https://github.com/vitaly-t/pg-promise/wiki/Common-Mistakes#redundant-named-parameter-re-referencing)

Also, instead of `any` you should use `none` for such query, because it returns no data.

**Comment by BryceKrah** [comment]
Fixed it, thank you for the tip!
